import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const attachmentAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From an Attachment Theory perspective, this text reveals patterns of relational dynamics and attachment styles. The content explores themes of connection, separation, security, and autonomy that reflect fundamental attachment needs. Narrative elements may demonstrate secure, anxious, avoidant, or disorganized attachment patterns in how relationships are portrayed. The emotional tone suggests underlying internal working models that shape expectations about self and others. The text potentially reveals how early attachment experiences continue to influence adult relationships through transference and projection. The writing style itself may reflect attachment patterns in its approach to engaging or distancing the reader.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through an Attachment Theory framework to reveal visual representations of relational dynamics and attachment styles. Compositional elements may suggest themes of connection, separation, security, and autonomy that reflect fundamental attachment needs. The spatial relationships between figures or objects potentially demonstrate secure, anxious, avoidant, or disorganized attachment patterns. Visual cues of emotional expression and proximity suggest underlying internal working models that shape expectations about self and others. The image potentially evokes attachment responses in the viewer that reflect their own relational patterns.",
    
    [MEDIA_TYPES.AUDIO]: "From an Attachment Theory perspective, this audio piece expresses relational dynamics and attachment patterns through its sonic qualities. Sound elements may suggest themes of connection, separation, security, and autonomy that reflect fundamental attachment needs. Rhythmic and tonal patterns potentially demonstrate secure, anxious, avoidant, or disorganized attachment styles in how sonic elements relate to each other. The emotional resonance suggests underlying internal working models that shape expectations about relationships. The piece potentially evokes attachment responses in the listener that reflect their own relational patterns. The structure of the audio may mirror attachment dynamics through patterns of approach and withdrawal.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through an Attachment Theory framework to reveal narrative and visual elements of relational dynamics and attachment styles. Character relationships demonstrate secure, anxious, avoidant, or disorganized attachment patterns in how connections, separations, and reunions are portrayed. The narrative potentially explores how early attachment experiences continue to influence adult relationships through transference and projection. Visual cues of emotional expression and proximity suggest underlying internal working models that shape expectations about self and others. The film's structure may mirror attachment dynamics through patterns of approach and withdrawal. The viewer's emotional response potentially reflects their own attachment patterns."
};
