import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const buddhistAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Buddhist perspective, this text reveals the nature of impermanence (anicca) and the absence of a permanent self (anatta). The content can be understood in terms of the Four Noble Truths, which address the nature of suffering (dukkha) and the path to its cessation. Narrative elements potentially demonstrate how attachment to fixed views and desires leads to suffering, while mindful awareness offers a path to liberation. The text may reveal interdependent arising (pratityasamutpada) in how phenomena emerge from complex conditions rather than existing independently. The writing potentially invites the reader into a state of present-moment awareness that transcends conceptual thinking.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Buddhist framework to reveal visual representations of impermanence (anicca), non-self (anatta), and the nature of suffering (dukkha). Compositional elements may suggest the interdependent arising (pratityasamutpada) of phenomena through visual relationships. The image potentially invites contemplation of emptiness (sunyata) through its play of form and space. Visual qualities may evoke states of mindful awareness or meditative absorption. The relationship between figure and ground potentially demonstrates the Middle Way between extremes of existence and non-existence. The viewer's experience of the image offers an opportunity for direct insight into the nature of perception and reality.",
    
    [MEDIA_TYPES.AUDIO]: "From a Buddhist perspective, this audio piece expresses the nature of impermanence (anicca) through its temporal unfolding. Sound elements demonstrate the interdependent arising (pratityasamutpada) of phenomena as sonic elements emerge from and dissolve into each other. The piece potentially invites the listener into a state of mindful awareness through its engagement with present-moment experience. Rhythmic and tonal patterns may reflect the Middle Way between extremes of existence and non-existence. The experience of listening offers an opportunity to observe how sounds arise and pass away without attachment, reflecting the Buddhist understanding of non-self (anatta) and the nature of suffering (dukkha).",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Buddhist framework to reveal narrative and visual elements of impermanence (anicca), non-self (anatta), and the nature of suffering (dukkha). Character arcs potentially demonstrate how attachment to fixed views and desires leads to suffering, while mindful awareness offers a path to liberation. Visual elements may suggest the interdependent arising (pratityasamutpada) of phenomena through compositional relationships. The film's temporal structure reflects the Buddhist understanding of impermanence as all things arise and pass away. The relationship between narrative and visual elements potentially demonstrates the Middle Way between extremes. The viewer's experience offers an opportunity for direct insight into the nature of perception and reality."
};
