import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const epicureanAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From an Epicurean perspective, this text explores themes related to the pursuit of pleasure understood as freedom from pain and mental disturbance (ataraxia). The content reveals insights about natural desires, the value of friendship, and the path to tranquility. The writing potentially demonstrates how understanding natural phenomena can free us from unnecessary fears and anxieties. There are suggestions of how simple living and limiting desires can lead to greater contentment. The text may explore how philosophical understanding contributes to a life of tranquility and modest pleasure.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through an Epicurean lens to reveal visual representations of pleasure, tranquility, natural desires, and the importance of friendship and community. Visual elements may suggest the value of simple pleasures and freedom from disturbance. The composition potentially reflects the Epicurean ideal of ataraxia—a state of mental tranquility free from fear and anxiety. Color relationships and spatial arrangements might express the distinction between necessary and unnecessary desires. The image potentially invites contemplation of natural phenomena as a way to dispel superstition and unnecessary fears.",
    
    [MEDIA_TYPES.AUDIO]: "From an Epicurean perspective, this audio piece expresses themes related to pleasure, tranquility, and the satisfaction of natural desires through its sonic qualities and emotional resonance. Sound elements may suggest the value of simple pleasures and freedom from disturbance. The structure of the piece potentially reflects the Epicurean ideal of ataraxia—a state of mental tranquility free from fear and anxiety. Rhythmic and tonal patterns might express the distinction between necessary and unnecessary desires. The piece potentially invites contemplation of natural phenomena as a way to dispel superstition and unnecessary fears.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through an Epicurean framework to reveal narrative and visual elements of pleasure, tranquility, natural desires, and the importance of friendship and community. Character relationships may explore the Epicurean understanding of friendship as an essential good. The narrative potentially demonstrates how understanding natural phenomena can free us from unnecessary fears and anxieties. Visual elements may suggest the value of simple pleasures and freedom from disturbance. The film's structure might reflect the Epicurean ideal of ataraxia—a state of mental tranquility free from fear and anxiety. The viewer is potentially invited to consider how limiting desires to what is natural and necessary can lead to greater contentment."
};
