import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const existentialAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From an Existential perspective, this text explores themes of freedom, choice, and the search for authentic meaning in an inherently meaningless universe. The content reveals the tension between existential anxiety and the human project of self-creation. Narrative elements potentially demonstrate how individuals confront the fundamental existential givens of death, freedom, isolation, and meaninglessness. The writing may explore the concept of authenticity as living in accordance with one's freely chosen values despite the absurdity of existence. The text potentially reveals how human beings create meaning through their choices and commitments in a world without predetermined essence or purpose.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through an Existential lens to reveal visual representations of freedom, authenticity, and the confrontation with nothingness that characterizes human existence. Compositional elements may suggest the tension between existential anxiety and the human project of self-creation. Visual cues potentially demonstrate how individuals confront the fundamental existential givens of death, freedom, isolation, and meaninglessness. The image may explore the concept of authenticity through its representation of human subjects or symbolic content. The visual language potentially reveals how human beings create meaning through their choices and commitments in a world without predetermined essence or purpose.",
    
    [MEDIA_TYPES.AUDIO]: "From an Existential perspective, this audio piece expresses the tension between freedom and anxiety, and the search for authentic meaning through its sonic qualities and emotional resonance. Sound elements may suggest the confrontation with nothingness that characterizes human existence. Rhythmic and tonal patterns potentially demonstrate how individuals navigate the fundamental existential givens of death, freedom, isolation, and meaninglessness. The structure of the piece may explore the concept of authenticity through its development and resolution. The sonic experience potentially reveals how human beings create meaning through their choices and commitments in a world without predetermined essence or purpose.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through an Existential framework to reveal narrative elements of freedom, choice, authenticity, and the human struggle to create meaning in an absurd universe. Character arcs potentially demonstrate how individuals confront the fundamental existential givens of death, freedom, isolation, and meaninglessness. The narrative may explore the concept of authenticity as living in accordance with one's freely chosen values despite the absurdity of existence. Visual techniques potentially represent the tension between existential anxiety and the human project of self-creation. The film's structure may reflect the non-linear, subjective nature of lived experience. The viewer is potentially invited to reflect on their own freedom, responsibility, and the creation of personal meaning."
};
