import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const gestaltAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Gestalt perspective, this text reveals the principles of wholeness and figure-ground relationships. The content can be understood in terms of contact boundaries, awareness processes, and the integration of polarities. The writing demonstrates how meaning emerges from the relationship between parts and wholes rather than from isolated elements. There are elements that suggest how awareness functions in the here-and-now to organize experience into meaningful gestalts. The text potentially reveals patterns of contact and withdrawal that characterize the relationship between self and environment. The work may demonstrate the paradoxical theory of change through its exploration of acceptance and transformation.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Gestalt framework to reveal visual principles of wholeness, figure-ground relationships, and the integration of polarities. Compositional elements demonstrate how perception organizes visual elements into meaningful wholes according to principles such as proximity, similarity, continuity, and closure. The image potentially reveals contact boundaries between visual elements that create meaningful distinctions while maintaining connection. Visual techniques may demonstrate the principle of prägnanz, where perception tends toward the simplest and most stable organization. The viewer's experience of the image involves an active process of gestalt formation that reveals how meaning emerges from relationship rather than isolated elements.",
    
    [MEDIA_TYPES.AUDIO]: "From a Gestalt perspective, this audio piece expresses principles of wholeness and figure-ground relationships through its sonic qualities and temporal unfolding. Sound elements demonstrate how auditory perception organizes sonic elements into meaningful wholes according to principles such as proximity, similarity, continuity, and closure. The piece potentially reveals patterns of contact and withdrawal through its dynamics of sound and silence. Rhythmic and tonal patterns may demonstrate the integration of polarities through tension and resolution. The structure of the piece potentially reveals how meaning emerges from the relationship between parts and wholes rather than from isolated elements. The listener's experience involves an active process of gestalt formation in the here-and-now.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Gestalt framework to reveal narrative and visual elements of wholeness, contact boundaries, awareness processes, and the integration of polarities. Character relationships demonstrate patterns of contact and withdrawal that characterize the relationship between self and environment. The narrative potentially reveals how awareness functions in the here-and-now to organize experience into meaningful gestalts. Visual techniques demonstrate principles of perception such as figure-ground relationships, proximity, similarity, continuity, and closure. The film's structure may reveal the paradoxical theory of change through its exploration of acceptance and transformation. The viewer's experience involves an active process of gestalt formation that reveals how meaning emerges from relationship rather than isolated elements."
};
