import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const irigarayianAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "An Irigarayian reading of this text reveals how it engages with or challenges phallogocentric discourse. The writing potentially demonstrates a feminine syntax that privileges multiplicity, fluidity, and proximity over linear logic and fixed meanings. There are moments where the text approaches feminine jouissance—a pleasure beyond the phallic economy of desire. The content explores sexual difference not as binary opposition but as radical alterity. The writing style may reflect the morphology of the female body through its rhythms, gaps, and fluid connections. The text potentially creates a space for feminine subjectivity that has been excluded from dominant philosophical and cultural discourses.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through an Irigarayian framework to reveal how it engages with or challenges phallogocentric visual language. Visual elements potentially demonstrate a feminine morphology that privileges multiplicity, fluidity, and proximity over linear perspective and fixed meanings. Compositional elements may reflect the specificity of female embodiment through formal qualities such as multiplicity, fluidity, and tactility. The image potentially creates a space for feminine jouissance—a pleasure beyond the phallic economy of desire. The relationship between figure and ground may challenge the subject-object division central to masculine visual economy. The viewer's relationship to the image potentially allows for an encounter with sexual difference as radical alterity.",
    
    [MEDIA_TYPES.AUDIO]: "An Irigarayian analysis of this audio piece reveals how it engages with or challenges phallogocentric sonic language. Sound elements potentially demonstrate a feminine morphology that privileges multiplicity, fluidity, and proximity over linear progression and fixed meanings. Rhythmic and tonal patterns may reflect the specificity of female embodiment through formal qualities such as multiplicity, fluidity, and tactility. The piece potentially creates a space for feminine jouissance—a pleasure beyond the phallic economy of desire. The relationship between figure and ground in the sonic landscape may challenge the subject-object division central to masculine economy. The listener's relationship to the sound potentially allows for an encounter with sexual difference as radical alterity.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through an Irigarayian framework to reveal how it engages with or challenges phallogocentric visual and narrative language. Visual and narrative elements potentially demonstrate a feminine morphology that privileges multiplicity, fluidity, and proximity over linear perspective and fixed meanings. Character relationships may explore sexual difference not as binary opposition but as radical alterity. The film potentially creates a space for feminine jouissance—a pleasure beyond the phallic economy of desire. Editing techniques and visual transitions may reflect the specificity of female embodiment through formal qualities such as multiplicity, fluidity, and tactility. The viewer's relationship to the film potentially allows for an encounter with feminine subjectivity that has been excluded from dominant cinematic discourses."
};
