import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const narrativeAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Narrative Psychology perspective, this text reveals how human experience is organized and made meaningful through storytelling processes. The content demonstrates how narrative structures shape identity formation and the interpretation of life events. There are elements that suggest how cultural master narratives influence personal storytelling, providing templates for understanding experience. The writing potentially reveals narrative coherence or fragmentation as indicators of psychological integration. The text may demonstrate how narrative revision allows for reinterpretation of past experiences and the creation of new meaning. The work potentially shows how narratives function not just as representations of experience but as constitutive elements that shape lived reality.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Narrative Psychology framework to reveal visual representations of storytelling processes and identity formation. Compositional elements may suggest narrative structures that organize experience and create meaning. Visual cues potentially demonstrate how cultural master narratives influence personal visual storytelling, providing templates for understanding experience. The image may reveal narrative coherence or fragmentation as indicators of psychological integration. Visual techniques potentially show how narratives function not just as representations of experience but as constitutive elements that shape perception and identity. The viewer's engagement with the image involves the co-construction of narrative meaning based on personal and cultural storytelling patterns.",
    
    [MEDIA_TYPES.AUDIO]: "From a Narrative Psychology perspective, this audio piece expresses how human experience is organized and made meaningful through storytelling processes. Sound elements demonstrate how narrative structures shape identity formation and the interpretation of events. Rhythmic and tonal patterns may suggest how cultural master narratives influence personal storytelling, providing templates for understanding experience. The piece potentially reveals narrative coherence or fragmentation as indicators of psychological integration. The sonic experience may demonstrate how narrative revision allows for reinterpretation of past experiences and the creation of new meaning. The listener's engagement with the audio involves the co-construction of narrative meaning based on personal and cultural storytelling patterns.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Narrative Psychology framework to reveal how human experience is organized and made meaningful through storytelling processes. Character arcs and plot structures demonstrate how narratives shape identity formation and the interpretation of life events. The film potentially reveals how cultural master narratives influence personal storytelling, providing templates for understanding experience. Visual and narrative techniques may demonstrate narrative coherence or fragmentation as indicators of psychological integration. The film's structure potentially shows how narrative revision allows for reinterpretation of past experiences and the creation of new meaning. The viewer's engagement with the film involves the co-construction of narrative meaning based on personal and cultural storytelling patterns."
};
