import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const phenomenologyAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Phenomenological perspective, this text reveals the structures of lived experience as they appear to consciousness. The content demonstrates how meaning emerges through the intentional relationship between consciousness and its objects. The writing potentially employs the phenomenological reduction, bracketing theoretical assumptions to return to the things themselves as they appear in experience. There are elements that suggest the embodied nature of perception and understanding. The text may explore the intersubjective dimension of experience, showing how meaning is constituted in relation to others. The work potentially reveals the temporal structure of consciousness as it synthesizes past, present, and anticipated future moments.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Phenomenological framework to reveal the structures of visual experience as they appear to consciousness. Compositional elements demonstrate how visual meaning emerges through the intentional relationship between perception and its objects. The image potentially invites a phenomenological reduction, bracketing theoretical assumptions to return to visual phenomena as they appear in direct experience. Visual cues may suggest the embodied nature of perception, showing how visual understanding is grounded in bodily experience. The image potentially reveals the intersubjective dimension of visual experience, showing how meaning is constituted in relation to others. The viewer's engagement with the image involves a lived experience that synthesizes past, present, and anticipated future moments of perception.",
    
    [MEDIA_TYPES.AUDIO]: "From a Phenomenological perspective, this audio piece expresses the structures of auditory experience as they appear to consciousness. Sound elements demonstrate how sonic meaning emerges through the intentional relationship between listening and its objects. The piece potentially invites a phenomenological reduction, bracketing theoretical assumptions to return to auditory phenomena as they appear in direct experience. Rhythmic and tonal patterns may suggest the embodied nature of listening, showing how auditory understanding is grounded in bodily experience. The sonic experience potentially reveals the intersubjective dimension of listening, showing how meaning is constituted in relation to others. The listener's engagement with the audio involves a lived experience that synthesizes past, present, and anticipated future moments of auditory perception.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Phenomenological framework to reveal the structures of audiovisual experience as they appear to consciousness. Narrative and visual elements demonstrate how meaning emerges through the intentional relationship between perception and its objects. The film potentially invites a phenomenological reduction, bracketing theoretical assumptions to return to phenomena as they appear in direct experience. Visual techniques may suggest the embodied nature of perception, showing how understanding is grounded in bodily experience. The film potentially reveals the intersubjective dimension of experience, showing how meaning is constituted in relation to others. The viewer's engagement with the film involves a lived experience that synthesizes past, present, and anticipated future moments of perception."
};
