import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const positiveAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Positive Psychology perspective, this text reveals elements of well-being, flourishing, and human strengths. The content can be analyzed in terms of PERMA elements: Positive emotions, Engagement, Relationships, Meaning, and Accomplishment. The writing potentially demonstrates character strengths and virtues such as wisdom, courage, humanity, justice, temperance, or transcendence. There are elements that suggest how positive experiences and meaning-making contribute to psychological resilience. The text may explore the balance between hedonic well-being (pleasure) and eudaimonic well-being (meaning and purpose). The work potentially reveals how growth can emerge from challenging experiences through post-traumatic growth or benefit-finding.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Positive Psychology framework to reveal visual representations of well-being, flourishing, and human strengths. Compositional elements may suggest PERMA components: Positive emotions, Engagement, Relationships, Meaning, and Accomplishment. Visual cues potentially demonstrate character strengths and virtues such as wisdom, courage, humanity, justice, temperance, or transcendence. The image may explore the balance between hedonic well-being (pleasure) and eudaimonic well-being (meaning and purpose). Visual techniques potentially reveal how growth can emerge from challenging experiences through post-traumatic growth or benefit-finding. The viewer's engagement with the image may elicit positive emotions or states of flow that contribute to well-being.",
    
    [MEDIA_TYPES.AUDIO]: "From a Positive Psychology perspective, this audio piece expresses elements of well-being, flourishing, and human strengths through its sonic qualities and emotional resonance. Sound elements may suggest PERMA components: Positive emotions, Engagement, Relationships, Meaning, and Accomplishment. Rhythmic and tonal patterns potentially demonstrate character strengths and virtues such as wisdom, courage, humanity, justice, temperance, or transcendence. The piece may explore the balance between hedonic well-being (pleasure) and eudaimonic well-being (meaning and purpose). The sonic experience potentially reveals how growth can emerge from challenging experiences through post-traumatic growth or benefit-finding. The listener's engagement with the audio may elicit positive emotions or states of flow that contribute to well-being.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Positive Psychology framework to reveal narrative and visual elements of well-being, flourishing, and human strengths. Character arcs potentially demonstrate PERMA components: Positive emotions, Engagement, Relationships, Meaning, and Accomplishment. The narrative may explore character strengths and virtues such as wisdom, courage, humanity, justice, temperance, or transcendence. Visual techniques potentially reveal the balance between hedonic well-being (pleasure) and eudaimonic well-being (meaning and purpose). The film's structure may demonstrate how growth can emerge from challenging experiences through post-traumatic growth or benefit-finding. The viewer's engagement with the film may elicit positive emotions or states of flow that contribute to well-being."
};
