import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const posthumanismAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Posthumanist perspective, this text challenges anthropocentric assumptions and explores the entanglements between human and nonhuman agencies. The content reveals how subjectivity is distributed across networks of human, technological, and material actors. The writing potentially demonstrates a critique of human exceptionalism and the nature/culture binary. There are elements that suggest how technology mediates and transforms human experience rather than serving as a mere tool. The text may explore how agency emerges from assemblages of human and nonhuman actors rather than from autonomous human subjects. The work potentially reveals the material agency of nonhuman entities and their participation in meaning-making processes.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Posthumanist framework to reveal visual representations of human-nonhuman entanglements, technological mediations, and hybrid forms of agency and subjectivity. Compositional elements may demonstrate a critique of human exceptionalism and the nature/culture binary. Visual cues potentially suggest how technology mediates and transforms human experience rather than serving as a mere tool. The image may explore cyborg or hybrid identities that challenge traditional boundaries between human, animal, and machine. Visual techniques potentially reveal the material agency of nonhuman entities and their participation in meaning-making processes. The viewer's relationship to the image involves a distributed form of perception that extends beyond the human subject.",
    
    [MEDIA_TYPES.AUDIO]: "From a Posthumanist perspective, this audio piece expresses the distributed nature of agency and subjectivity across human and nonhuman actors through its sonic qualities and technological mediations. Sound elements demonstrate a critique of human exceptionalism and the nature/culture binary. Rhythmic and tonal patterns potentially suggest how technology mediates and transforms human experience rather than serving as a mere tool. The piece may explore how agency emerges from assemblages of human and nonhuman sonic actors rather than from autonomous human subjects. The sonic experience potentially reveals the material agency of nonhuman entities and their participation in meaning-making processes. The listener's relationship to the audio involves a distributed form of perception that extends beyond the human subject.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Posthumanist framework to reveal narrative and visual elements that challenge anthropocentrism and explore the entanglements between human, technological, and nonhuman agencies. Character relationships potentially demonstrate a critique of human exceptionalism and the nature/culture binary. The narrative may explore cyborg or hybrid identities that challenge traditional boundaries between human, animal, and machine. Visual techniques potentially suggest how technology mediates and transforms human experience rather than serving as a mere tool. The film's structure may reveal how agency emerges from assemblages of human and nonhuman actors rather than from autonomous human subjects. The viewer's relationship to the film involves a distributed form of perception that extends beyond the human subject."
};
