import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const tackticalAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Tacktical Methodology perspective, this text reveals patterns of tactical engagement with established structures and systems. The content demonstrates how individuals navigate and repurpose dominant cultural forms through everyday practices and creative appropriation. The writing potentially shows how tactical operations work within strategic spaces, finding opportunities for resistance and creative expression. There are elements that suggest how meaning emerges through use rather than through predetermined structures. The text may explore the temporal nature of tactics as they seize opportunities in the moment. The work potentially reveals how power operates through both strategic impositions and tactical responses.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Tacktical Methodology framework to reveal visual representations of tactical engagement with established structures and systems. Compositional elements may demonstrate how individuals navigate and repurpose dominant visual languages through creative appropriation. Visual cues potentially show how tactical operations work within strategic spaces, finding opportunities for resistance and creative expression. The image may explore how meaning emerges through use rather than through predetermined structures. Visual techniques potentially reveal the temporal nature of tactics as they seize opportunities in the moment. The viewer's relationship to the image involves a tactical reading that finds spaces for alternative interpretations within dominant visual codes.",
    
    [MEDIA_TYPES.AUDIO]: "From a Tacktical Methodology perspective, this audio piece expresses patterns of tactical engagement with established structures and systems through its sonic qualities. Sound elements demonstrate how individuals navigate and repurpose dominant auditory forms through everyday practices and creative appropriation. Rhythmic and tonal patterns potentially show how tactical operations work within strategic spaces, finding opportunities for resistance and creative expression. The piece may explore how meaning emerges through use rather than through predetermined structures. The sonic experience potentially reveals the temporal nature of tactics as they seize opportunities in the moment. The listener's relationship to the audio involves a tactical hearing that finds spaces for alternative interpretations within dominant sonic codes.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Tacktical Methodology framework to reveal narrative and visual elements of tactical engagement with established structures and systems. Character relationships potentially demonstrate how individuals navigate and repurpose dominant cultural forms through everyday practices and creative appropriation. The narrative may show how tactical operations work within strategic spaces, finding opportunities for resistance and creative expression. Visual techniques potentially explore how meaning emerges through use rather than through predetermined structures. The film's structure may reveal the temporal nature of tactics as they seize opportunities in the moment. The viewer's relationship to the film involves a tactical reading that finds spaces for alternative interpretations within dominant cinematic codes."
};
