import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const cbtAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Cognitive-Behavioral perspective, this text reveals patterns of thinking that may include cognitive distortions such as all-or-nothing thinking, overgeneralization, or emotional reasoning. The content demonstrates the relationship between thoughts, emotions, and behaviors, showing how cognitive patterns influence emotional responses and behavioral choices. Narrative elements potentially reveal core beliefs and schemas about self, others, and the world that shape interpretation of events. The text may demonstrate adaptive or maladaptive coping strategies in response to challenging situations. The writing potentially offers opportunities for cognitive restructuring by presenting alternative perspectives or challenging irrational beliefs.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Cognitive-Behavioral framework to reveal visual representations of cognitive patterns, emotional responses, and behavioral tendencies. Compositional elements may suggest cognitive distortions such as mental filtering, catastrophizing, or personalization through selective focus or exaggerated elements. Visual cues potentially evoke emotional responses that demonstrate the connection between perception, interpretation, and feeling. The image may represent core beliefs and schemas about self, others, and the world through symbolic content. The viewer's response to the image offers an opportunity to observe automatic thoughts and practice cognitive restructuring.",
    
    [MEDIA_TYPES.AUDIO]: "From a Cognitive-Behavioral perspective, this audio piece expresses patterns of thinking, emotional responses, and behavioral tendencies through its sonic qualities. Sound elements may suggest cognitive patterns such as rumination, worry, or adaptive problem-solving through repetitive or resolving structures. Rhythmic and tonal patterns potentially evoke emotional responses that demonstrate the connection between perception, interpretation, and feeling. The structure of the piece may represent adaptive or maladaptive coping strategies through tension and resolution. The listener's response to the audio offers an opportunity to observe automatic thoughts and practice cognitive restructuring.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Cognitive-Behavioral framework to reveal narrative and visual elements of cognitive patterns, emotional responses, and behavioral tendencies. Character arcs potentially demonstrate how thoughts influence emotions and behaviors, showing the consequences of cognitive distortions or the benefits of cognitive restructuring. Narrative elements may reveal core beliefs and schemas about self, others, and the world that shape interpretation of events. Visual techniques potentially represent internal cognitive processes such as rumination, worry, or adaptive problem-solving. The film may demonstrate adaptive or maladaptive coping strategies in response to challenging situations. The viewer's response offers an opportunity to observe automatic thoughts and practice perspective-taking."
};
