import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const criticalAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Critical Theory perspective, this text reveals underlying power structures and ideological formations. The content can be analyzed dialectically to understand how it both reproduces and potentially challenges dominant social relations. The writing demonstrates how cultural products are shaped by historical and material conditions rather than existing as autonomous expressions. There are elements that suggest how ideology functions to naturalize social arrangements that serve particular interests. The text potentially contains contradictions that reveal the tensions within current social formations. The work can be understood as a form of praxis that either reinforces hegemonic power or creates spaces for emancipatory consciousness.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through Critical Theory to reveal visual representations of power structures, ideological formations, and the potential for emancipatory consciousness. Compositional elements may demonstrate how visual language is shaped by historical and material conditions rather than existing as autonomous expression. The image potentially functions as a form of reification that naturalizes social arrangements or as a dialectical representation that reveals contradictions within current social formations. Visual techniques may reveal how cultural products both reproduce and potentially challenge dominant social relations. The viewer's relationship to the image is mediated by ideological formations that shape perception and interpretation.",
    
    [MEDIA_TYPES.AUDIO]: "From a Critical Theory perspective, this audio piece expresses the tension between domination and emancipation through its sonic qualities and structural elements. Sound components demonstrate how cultural products are shaped by historical and material conditions rather than existing as autonomous expressions. The piece potentially functions as a form of reification that naturalizes social arrangements or as a dialectical representation that reveals contradictions within current social formations. Rhythmic and tonal patterns may reveal how cultural products both reproduce and potentially challenge dominant social relations. The listener's relationship to the sound is mediated by ideological formations that shape perception and interpretation.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through Critical Theory to reveal narrative and visual elements of power structures, ideological formations, and the dialectical relationship between domination and emancipation. Character relationships and social dynamics demonstrate how cultural products are shaped by historical and material conditions rather than existing as autonomous expressions. The film potentially functions as a form of reification that naturalizes social arrangements or as a dialectical representation that reveals contradictions within current social formations. Visual and narrative techniques may reveal how cultural products both reproduce and potentially challenge dominant social relations. The viewer's relationship to the film is mediated by ideological formations that shape perception and interpretation."
};
