import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const deleuzianAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Deleuzian perspective, this text operates as an assemblage of heterogeneous elements, creating rhizomatic connections rather than hierarchical structures. The content reveals lines of flight that deterritorialize fixed meanings and identities, opening up new possibilities for becoming. The writing demonstrates the productive nature of desire as a force of creation rather than lack. Multiple voices and perspectives suggest a nomadic subjectivity that resists fixed identity positions. The text functions as a body without organs, a surface of intensities rather than organized meaning. Recurring motifs operate as refrains that temporarily organize territories of meaning before dissolving into new configurations.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed as a Deleuzian assemblage of visual elements that create rhizomatic connections rather than hierarchical structures. Visual components function as intensities on a plane of consistency, creating affects that operate below the level of representation. The composition suggests lines of flight that deterritorialize fixed meanings and open up new possibilities for becoming. Color relationships and spatial arrangements can be understood as expressions of desire as a productive force rather than lack. The image potentially functions as a body without organs, a surface of intensities rather than organized meaning. The viewer's encounter with the image creates a becoming-other that transforms both viewer and image.",
    
    [MEDIA_TYPES.AUDIO]: "From a Deleuzian perspective, this audio piece functions as an assemblage of sonic elements that create rhizomatic connections rather than hierarchical structures. Sound operates as intensities on a plane of consistency, creating affects that work below the level of representation. Rhythmic and tonal patterns suggest lines of flight that deterritorialize fixed meanings and open up new possibilities for becoming. The structure of the piece demonstrates the productive nature of desire as a force of creation rather than lack. Recurring motifs operate as refrains that temporarily organize territories of meaning before dissolving into new configurations. The listener's encounter with the sound creates a becoming-other that transforms both listener and sound.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed as a Deleuzian assemblage of visual, narrative, and sonic elements that create rhizomatic connections rather than hierarchical structures. The film operates through movement-images and time-images that directly present duration rather than representing it. Visual components function as intensities on a plane of consistency, creating affects that operate below the level of representation. The narrative suggests lines of flight that deterritorialize fixed meanings and identities, opening up new possibilities for becoming. Character relationships demonstrate nomadic subjectivity that resists fixed identity positions. Editing techniques and visual transitions can be understood as expressions of desire as a productive force rather than lack."
};
