import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const feministAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Feminist perspective, this text reveals the social construction of gender and the operation of patriarchal structures. The content can be analyzed through various feminist lenses to understand how gender shapes experience and social relations. The writing potentially demonstrates how language and narrative forms have been shaped by gendered power dynamics. There are elements that suggest how intersecting identities of race, class, sexuality, and ability influence gendered experience. The text may challenge or reinforce traditional gender roles and expectations. The work potentially creates space for marginalized voices and experiences that have been excluded from dominant cultural narratives.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Feminist framework to reveal visual representations of gender construction, patriarchal structures, and the potential for resistance and transformation. Compositional elements may demonstrate how visual language has been shaped by gendered power dynamics and the male gaze. The image potentially challenges or reinforces traditional gender roles and expectations through its representation of bodies, spaces, and relationships. Visual techniques may reveal how intersecting identities of race, class, sexuality, and ability influence gendered experience. The viewer's relationship to the image is mediated by gendered patterns of looking and being looked at. The work potentially creates space for marginalized perspectives that have been excluded from dominant visual culture.",
    
    [MEDIA_TYPES.AUDIO]: "From a Feminist perspective, this audio piece expresses gendered experiences and the potential for challenging patriarchal structures through its sonic qualities and emotional resonance. Sound elements may demonstrate how auditory expression has been shaped by gendered power dynamics. The piece potentially challenges or reinforces traditional gender roles and expectations through its sonic representation of voices, spaces, and relationships. Rhythmic and tonal patterns may reveal how intersecting identities of race, class, sexuality, and ability influence gendered experience. The listener's relationship to the sound is mediated by gendered patterns of speaking and listening. The work potentially creates space for marginalized voices that have been excluded from dominant auditory culture.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Feminist framework to reveal narrative and visual elements of gender construction, patriarchal structures, and the potential for feminist resistance and transformation. Character relationships and social dynamics demonstrate how visual and narrative language has been shaped by gendered power dynamics and the male gaze. The film potentially challenges or reinforces traditional gender roles and expectations through its representation of bodies, spaces, and relationships. Visual and narrative techniques may reveal how intersecting identities of race, class, sexuality, and ability influence gendered experience. The viewer's relationship to the film is mediated by gendered patterns of looking and being looked at. The work potentially creates space for marginalized perspectives that have been excluded from dominant cinema."
};
