import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const hermeneuticsAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Hermeneutic perspective, this text reveals layers of meaning that emerge through the interpretive circle of part and whole. The content can be understood in terms of its historical context, linguistic dimensions, and the fusion of horizons between text and interpreter. The writing demonstrates how understanding is always situated within traditions and pre-understandings that shape interpretation. There are elements that suggest how language functions not merely as a tool but as the medium in which understanding occurs. The text potentially reveals the temporal nature of understanding as a dialogue between past and present. The work invites a process of interpretation that acknowledges both the historical distance and the productive application of meaning to the interpreter's situation.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Hermeneutic framework to reveal visual meanings that emerge through the interpretive circle of part and whole, historical context, and the fusion of horizons between image and viewer. Compositional elements demonstrate how visual understanding is always situated within traditions and pre-understandings that shape interpretation. The image potentially reveals the temporal nature of understanding as a dialogue between past and present visual languages. Visual techniques may demonstrate how meaning emerges not from isolated elements but from their relationships within broader contexts. The viewer's engagement with the image involves a fusion of horizons where the historical world of the image meets the present situation of the interpreter. The work invites a process of interpretation that acknowledges both historical distance and productive application.",
    
    [MEDIA_TYPES.AUDIO]: "From a Hermeneutic perspective, this audio piece expresses meanings that emerge through the interpretive circle of part and whole, historical context, and the fusion of horizons between sound and listener. Sound elements demonstrate how auditory understanding is always situated within traditions and pre-understandings that shape interpretation. The piece potentially reveals the temporal nature of understanding as a dialogue between past and present sonic languages. Rhythmic and tonal patterns may demonstrate how meaning emerges not from isolated elements but from their relationships within broader contexts. The listener's engagement with the audio involves a fusion of horizons where the historical world of the sound meets the present situation of the interpreter. The work invites a process of interpretation that acknowledges both historical distance and productive application.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Hermeneutic framework to reveal narrative and visual meanings that emerge through the interpretive circle of part and whole, historical context, and the fusion of horizons between film and viewer. Character relationships and narrative elements demonstrate how understanding is always situated within traditions and pre-understandings that shape interpretation. The film potentially reveals the temporal nature of understanding as a dialogue between past and present visual and narrative languages. Visual techniques may demonstrate how meaning emerges not from isolated elements but from their relationships within broader contexts. The viewer's engagement with the film involves a fusion of horizons where the historical world of the film meets the present situation of the interpreter. The work invites a process of interpretation that acknowledges both historical distance and productive application."
};
