import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const jungianAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Jungian perspective, this text reveals archetypal patterns and symbolic expressions of the collective unconscious. The content can be understood in terms of the individuation process, as the ego relates to both personal and collective unconscious material. The writing potentially demonstrates the interplay of various archetypes such as the Shadow, Anima/Animus, Self, or the Hero's journey. There are elements that suggest how symbolic language expresses psychic content that cannot be directly articulated. The text may reveal the transcendent function as it mediates between conscious and unconscious, creating new symbolic syntheses. The work potentially demonstrates synchronistic connections that reveal meaningful patterns beyond causal explanation.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Jungian framework to reveal archetypal patterns and symbolic expressions of the collective unconscious. Visual elements potentially represent archetypes such as the Shadow, Anima/Animus, Self, or stages of the Hero's journey. The composition may demonstrate the mandala structure as an expression of psychic wholeness and integration. Color relationships and symbolic content potentially express psychic material that cannot be directly articulated. The image may function as a container for projection of unconscious content, revealing aspects of the viewer's psyche. The visual language potentially demonstrates the transcendent function as it mediates between conscious and unconscious, creating new symbolic syntheses.",
    
    [MEDIA_TYPES.AUDIO]: "From a Jungian perspective, this audio piece expresses archetypal patterns and symbolic expressions of the collective unconscious through its sonic qualities and emotional resonance. Sound elements potentially represent archetypes such as the Shadow, Anima/Animus, Self, or stages of the Hero's journey. Rhythmic and tonal patterns may demonstrate the mandala structure as an expression of psychic wholeness and integration. The sonic experience potentially expresses psychic material that cannot be directly articulated. The piece may function as a container for projection of unconscious content, revealing aspects of the listener's psyche. The auditory language potentially demonstrates the transcendent function as it mediates between conscious and unconscious, creating new symbolic syntheses.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Jungian framework to reveal narrative and visual elements of archetypal patterns and symbolic expressions of the collective unconscious. Character relationships potentially represent archetypes such as the Shadow, Anima/Animus, Self, or stages of the Hero's journey. The narrative structure may demonstrate the individuation process as characters integrate conscious and unconscious aspects of the psyche. Visual techniques potentially express psychic material that cannot be directly articulated. The film may function as a container for projection of unconscious content, revealing aspects of the viewer's psyche. The visual and narrative language potentially demonstrates the transcendent function as it mediates between conscious and unconscious, creating new symbolic syntheses."
};
