import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const nietzscheanAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Nietzschean perspective, this text expresses the will to power as a creative force of self-overcoming. The content reveals a perspectival understanding of truth that goes beyond conventional moral categories of good and evil. The writing potentially demonstrates the tension between Apollonian form and Dionysian creative energy. There are elements that suggest a transvaluation of values, challenging established moral and metaphysical assumptions. The text may explore the concept of eternal recurrence as the ultimate affirmation of life. The work potentially embodies Nietzsche's call for a philosophy that serves life and enhances human potential rather than diminishing vital forces.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Nietzschean framework to reveal visual expressions of the will to power, perspectivism, and the potential for going beyond conventional moral interpretations. Compositional elements may demonstrate the tension between Apollonian form and Dionysian creative energy. Visual cues potentially suggest a transvaluation of values, challenging established aesthetic and moral assumptions. The image may embody the concept of amor fati—the love of fate and affirmation of life with all its suffering and joy. The visual language potentially expresses Nietzsche's emphasis on becoming rather than being, showing reality as a dynamic process rather than a fixed state. The viewer's encounter with the image involves a perspectival interpretation that reveals the impossibility of absolute truth.",
    
    [MEDIA_TYPES.AUDIO]: "From a Nietzschean perspective, this audio piece expresses the will to power as a creative force and the affirmation of life through its sonic qualities and emotional resonance. Sound elements demonstrate the tension between Apollonian form and Dionysian creative energy. Rhythmic and tonal patterns potentially suggest a transvaluation of values, challenging established musical and aesthetic assumptions. The piece may embody the concept of eternal recurrence through cyclical structures that affirm repetition as creative rather than merely mechanical. The sonic experience potentially expresses Nietzsche's emphasis on becoming rather than being, showing reality as a dynamic process rather than a fixed state. The listener's encounter with the sound involves a perspectival interpretation that reveals the impossibility of absolute truth.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Nietzschean framework to reveal narrative and visual elements of the will to power, eternal recurrence, and the transvaluation of conventional moral values. Character arcs potentially demonstrate the process of self-overcoming and the creation of new values beyond good and evil. The narrative may explore the tension between Apollonian form and Dionysian creative energy. Visual techniques potentially express Nietzsche's emphasis on becoming rather than being, showing reality as a dynamic process rather than a fixed state. The film's structure may embody the concept of amor fati—the love of fate and affirmation of life with all its suffering and joy. The viewer's encounter with the film involves a perspectival interpretation that reveals the impossibility of absolute truth."
};
