import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const psychiatryAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Psychiatric perspective, this text reveals themes that can be understood in terms of diagnostic categories, neurobiological factors, and psychosocial determinants. The content can be analyzed using the biopsychosocial model that integrates multiple levels of explanation. The writing potentially demonstrates psychological processes that may relate to mental health and illness. There are elements that suggest how biological, psychological, and social factors interact in shaping human experience. The text may explore themes related to specific psychiatric conditions or general mental health concerns. The work potentially reveals how narrative and meaning-making processes contribute to psychological well-being or distress.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Psychiatric framework to reveal visual representations of psychological states, neurobiological processes, and psychosocial factors that contribute to mental health and illness. Compositional elements may suggest emotional states or cognitive patterns that relate to psychological functioning. Visual cues potentially demonstrate how biological, psychological, and social factors interact in shaping human experience. The image may explore themes related to specific psychiatric conditions or general mental health concerns. Visual techniques potentially reveal how perception and interpretation processes contribute to psychological well-being or distress. The viewer's response to the image may provide insights into psychological processes such as projection, identification, or emotional regulation.",
    
    [MEDIA_TYPES.AUDIO]: "From a Psychiatric perspective, this audio piece expresses themes related to psychological states, neurobiological processes, and psychosocial factors through its sonic qualities and emotional resonance. Sound elements may suggest emotional states or cognitive patterns that relate to psychological functioning. Rhythmic and tonal patterns potentially demonstrate how biological, psychological, and social factors interact in shaping human experience. The piece may explore themes related to specific psychiatric conditions or general mental health concerns. The sonic experience potentially reveals how auditory processing and interpretation contribute to psychological well-being or distress. The listener's response to the audio may provide insights into psychological processes such as emotional regulation, attention, or memory.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Psychiatric framework to reveal narrative and visual elements of psychological states, neurobiological processes, and psychosocial factors that contribute to mental health and illness. Character arcs potentially demonstrate how biological, psychological, and social factors interact in shaping human experience. The narrative may explore themes related to specific psychiatric conditions or general mental health concerns. Visual techniques potentially reveal how perception, cognition, and emotion interact in psychological functioning. The film's structure may demonstrate psychological processes such as memory, attention, or executive functioning. The viewer's response to the film may provide insights into psychological processes such as empathy, identification, or emotional regulation."
};
