import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const stoicismAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Stoic perspective, this text reveals themes related to virtue, the dichotomy of control, and living according to rational nature. The content can be understood in terms of the Stoic emphasis on focusing on what is within our control and maintaining a cosmic perspective. The writing potentially demonstrates the four cardinal virtues of wisdom, courage, justice, and temperance. There are elements that suggest how emotional responses are shaped by judgments rather than external events. The text may explore the concept of amor fati—the acceptance and love of one's fate. The work potentially reveals how philosophical understanding contributes to tranquility (ataraxia) and emotional resilience.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Stoic framework to reveal visual representations of virtue, the dichotomy of control, and the cosmic perspective that characterizes Stoic philosophy. Compositional elements may suggest the four cardinal virtues of wisdom, courage, justice, and temperance. Visual cues potentially demonstrate the Stoic emphasis on focusing on what is within our control and maintaining equanimity toward external circumstances. The image may explore the concept of memento mori—the reminder of mortality that puts daily concerns into perspective. Visual techniques potentially reveal how philosophical understanding contributes to tranquility (ataraxia) and emotional resilience. The viewer's relationship to the image offers an opportunity to practice the Stoic discipline of assent—choosing how to interpret and respond to impressions.",
    
    [MEDIA_TYPES.AUDIO]: "From a Stoic perspective, this audio piece expresses themes related to virtue, the dichotomy of control, and living according to rational nature through its sonic qualities and emotional resonance. Sound elements may suggest the four cardinal virtues of wisdom, courage, justice, and temperance. Rhythmic and tonal patterns potentially demonstrate the Stoic emphasis on focusing on what is within our control and maintaining equanimity toward external circumstances. The piece may explore the concept of amor fati—the acceptance and love of one's fate. The sonic experience potentially reveals how philosophical understanding contributes to tranquility (ataraxia) and emotional resilience. The listener's relationship to the audio offers an opportunity to practice the Stoic discipline of assent—choosing how to interpret and respond to impressions.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Stoic framework to reveal narrative and visual elements of virtue, the dichotomy of control, and the cosmic perspective that characterizes Stoic philosophy. Character arcs potentially demonstrate the four cardinal virtues of wisdom, courage, justice, and temperance. The narrative may explore how emotional responses are shaped by judgments rather than external events. Visual techniques potentially reveal the Stoic emphasis on focusing on what is within our control and maintaining equanimity toward external circumstances. The film's structure may explore concepts such as memento mori or amor fati that put daily concerns into perspective. The viewer's relationship to the film offers an opportunity to practice the Stoic discipline of assent—choosing how to interpret and respond to impressions."
};
