import { MEDIA_TYPES } from '../constants';
import { PredefinedAnalyses } from './index';

export const transpersonalAnalyses: PredefinedAnalyses = {
    [MEDIA_TYPES.TEXT]: "From a Transpersonal perspective, this text explores dimensions of experience that transcend the boundaries of the ego. The content reveals potential states of consciousness that connect the individual to spiritual, cosmic, or universal dimensions of existence. The writing potentially demonstrates how identity can expand beyond the personal self to include broader aspects of humanity, nature, or consciousness itself. There are elements that suggest how non-ordinary states of consciousness can provide access to transpersonal insights and transformative experiences. The text may explore spiritual or mystical themes that point toward the integration of psychological and spiritual dimensions of human experience. The work potentially reveals how personal development can lead toward self-transcendence and higher states of consciousness.",
    
    [MEDIA_TYPES.IMAGE]: "This image can be analyzed through a Transpersonal framework to reveal visual representations of experiences that transcend ordinary ego boundaries and connect to spiritual or cosmic dimensions. Compositional elements may suggest states of consciousness that go beyond everyday awareness to include transpersonal realms. Visual cues potentially demonstrate how identity can expand beyond the personal self to include broader aspects of humanity, nature, or consciousness itself. The image may explore spiritual or mystical themes that point toward the integration of psychological and spiritual dimensions of human experience. Visual techniques potentially reveal how personal development can lead toward self-transcendence and higher states of consciousness. The viewer's engagement with the image may evoke non-ordinary states of awareness that provide access to transpersonal insights.",
    
    [MEDIA_TYPES.AUDIO]: "From a Transpersonal perspective, this audio piece expresses states of consciousness that transcend ordinary ego boundaries through its sonic qualities and emotional resonance. Sound elements suggest dimensions of experience that connect the individual to spiritual, cosmic, or universal aspects of existence. Rhythmic and tonal patterns potentially demonstrate how identity can expand beyond the personal self to include broader aspects of humanity, nature, or consciousness itself. The piece may explore spiritual or mystical themes that point toward the integration of psychological and spiritual dimensions of human experience. The sonic experience potentially reveals how personal development can lead toward self-transcendence and higher states of consciousness. The listener's engagement with the audio may evoke non-ordinary states of awareness that provide access to transpersonal insights.",
    
    [MEDIA_TYPES.FILM]: "This film can be analyzed through a Transpersonal framework to reveal narrative and visual elements of experiences that transcend ordinary ego boundaries and connect to spiritual or cosmic dimensions. Character arcs potentially demonstrate how identity can expand beyond the personal self to include broader aspects of humanity, nature, or consciousness itself. The narrative may explore spiritual or mystical themes that point toward the integration of psychological and spiritual dimensions of human experience. Visual techniques potentially suggest non-ordinary states of consciousness that provide access to transpersonal insights and transformative experiences. The film's structure may reveal how personal development can lead toward self-transcendence and higher states of consciousness. The viewer's engagement with the film may evoke expanded states of awareness that transcend everyday perception."
};
